topComment = """
# Generated by smoothieware-config module available:
# https://github.com/mr-smooth/smoothieware-config
#
# DO NOT MANUALLY MODIFY this file as it is automatically genrated
# and is likely to be overriden in the future.

# CONFIG BEGIN

"""
module.exports = ()->
    (input, includeComments=true)->
        output = if includeComments then topComment else ""

        for key in Object.keys(input)
            output += "#{key}\t\t\t#{input[key]}\n"

        output += '# CONFIG END' if includeComments
        return output
